source 'http://rubygems.org'

gem 'rails', '3.2.0.rc2'

gem 'haml-rails'
gem 'jquery-rails'
gem 'devise'
gem 'simple_form'
gem 'kaminari'
gem 'mysql2'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
	#gem 'sass-rails',   '~> 3.2.3'
	#gem 'coffee-rails', '~> 3.2.0'
	gem 'uglifier', '>= 1.0.3'
end

group :production do
  gem 'therubyracer'
end

group :development, :test do
  gem 'unicorn'
  gem 'sqlite3'
  gem 'ruby-debug19', :require => 'ruby-debug'
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'rails3-generators'
  gem 'shoulda-matchers'
  gem "spork", "~> 0.9.0.rc4 "
  gem "guard-spork"
  gem "guard-rspec"
end
