source 'http://rubygems.org'

gem 'rails', '3.1.1'

gem 'haml-rails'
gem 'jquery-rails'
gem 'devise'
gem 'simple_form'
gem 'kaminari'
gem 'mysql2'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.1.4'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

group :development, :test do
  gem 'unicorn'
  gem 'sqlite3'
  gem 'ruby-debug19', :require => 'ruby-debug'
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'rails3-generators'
  gem 'shoulda-matchers'
  gem "spork", "> 0.9.0.rc"
  gem "guard-spork"
  gem "guard-rspec"
end
