source 'http://rubygems.org'

gem 'rails', '3.1.0.beta1'
gem 'haml-rails', '0.3.4'
gem 'devise', '1.3.4'
gem 'simple_form', '1.3.1'
gem 'mysql2', '0.3.2'

# Asset template engines
gem 'sass', '3.1.1'
gem 'uglifier', '0.5.3'

gem 'jquery-rails', '1.0.2'

group :development, :test do
  gem 'unicorn', '3.6.2'
  gem 'ruby-debug19', '0.11.6', :require => 'ruby-debug'
  gem 'rails3-generators', '0.17.4'
  gem 'sqlite3', '1.3.3'
  gem 'rspec-rails', '2.6.0'
  gem 'factory_girl_rails', '1.0.1'
  gem 'shoulda-matchers', '1.0.0.beta2'
end